version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
    command: ["./wait-for-it.sh", "db", "--", "gunicorn", "--bind", "0.0.0.0:5000", "app.app:create_app()"]

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
